[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plant_analysis_avll"
authors = [{name = "Uday Santhosh Raju Vysyaraju", email = "uday@tamu.edu"}]
dynamic = ["version", "description"]
